//
//  GenerateTestListTests.swift
//  IceTests
//
//  Created by Jake Heiser on 11/25/18.
//

import TestingUtilities
import XCTest

class GenerateTestListTests: XCTestCase {

    func testGenerate() {
        let icebox = IceBox(template: .lib)
        
        let result = icebox.run("generate-test-list")
        
        Differentiate.byPlatform(mac: {
            IceAssertEqual(result.exitStatus, 0)
            IceAssertEqual(result.stderr, "")
            IceAssertEqual(result.stdout, """
            Compile Lib/Lib.swift
            Merge Lib
            Compile LibTests/LibTests.swift
            Merge LibTests
            Link LibPackageTests
            
            """)
            
            IceAssertEqual(icebox.fileContents("Tests/LinuxMain.swift"), """
            import XCTest
            
            import LibTests
            
            var tests = [XCTestCaseEntry]()
            tests += LibTests.__allTests()
            
            XCTMain(tests)

            """)
            
            IceAssertEqual(icebox.fileContents("Tests/LibTests/XCTestManifests.swift"), """
            #if !canImport(ObjectiveC)
            import XCTest
            
            extension LibTests {
                // DO NOT MODIFY: This is autogenerated, use:
                //   `swift test --generate-linuxmain`
                // to regenerate.
                static let __allTests__LibTests = [
                    ("testExample", testExample),
                ]
            }

            public func __allTests() -> [XCTestCaseEntry] {
                return [
                    testCase(LibTests.__allTests__LibTests),
                ]
            }
            #endif
            
            """)
        }, linux: {
            IceAssertEqual(result.exitStatus, 1)
            IceAssertEqual(result.stdout, "")
            IceAssertEqual(result.stderr, """

            Error: test list generation is not supported on Linux


            """)
        })
    }

}
