#if !canImport(ObjectiveC)
import XCTest

extension AddTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AddTests = [
        ("testBasicAdd", testBasicAdd),
        ("testBranchAdd", testBranchAdd),
        ("testDifferentNamedLib", testDifferentNamedLib),
        ("testSHAAdd", testSHAAdd),
        ("testSingleTargetAdd", testSingleTargetAdd),
        ("testTargetAdd", testTargetAdd),
        ("testVersionedAdd", testVersionedAdd),
    ]
}

extension BuildTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BuildTests = [
        ("testBuildErrors", testBuildErrors),
        ("testBuildProduct", testBuildProduct),
        ("testBuildTarget", testBuildTarget),
        ("testCleanBuild", testCleanBuild),
        ("testReleaseBuild", testReleaseBuild),
        ("testSimpleBuild", testSimpleBuild),
        ("testWatchBuild", testWatchBuild),
    ]
}

extension CleanTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CleanTests = [
        ("testClean", testClean),
    ]
}

extension ConfigTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ConfigTests = [
        ("testGet", testGet),
        ("testSet", testSet),
        ("testSetInvalid", testSetInvalid),
        ("testShow", testShow),
    ]
}

extension DumpTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DumpTests = [
        ("testDump", testDump),
    ]
}

extension GenerateTestListTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GenerateTestListTests = [
        ("testGenerate", testGenerate),
    ]
}

extension InitTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__InitTests = [
        ("testExec", testExec),
        ("testLib", testLib),
    ]
}

extension NewTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NewTests = [
        ("testExec", testExec),
        ("testLib", testLib),
    ]
}

extension OutdatedTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__OutdatedTests = [
        ("testOutdated", testOutdated),
        ("testOutdatedNoDependencies", testOutdatedNoDependencies),
    ]
}

extension ProductTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ProductTests = [
        ("testAddExec", testAddExec),
        ("testAddLib", testAddLib),
        ("testRemove", testRemove),
    ]
}

extension RegistryTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RegistryTests = [
        ("testAdd", testAdd),
        ("testLocalLookup", testLocalLookup),
        ("testRemove", testRemove),
        ("testSharedLookup", testSharedLookup),
    ]
}

extension RemoveTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RemoveTests = [
        ("testBasicRemove", testBasicRemove),
        ("testRemoveDifferentName", testRemoveDifferentName),
    ]
}

extension ResolveTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ResolveTests = [
        ("testResolve", testResolve),
    ]
}

extension RunTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RunTests = [
        ("testBasicRun", testBasicRun),
        ("testWatchRun", testWatchRun),
    ]
}

extension SearchTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SearchTests = [
        ("testFullSearch", testFullSearch),
        ("testNameSearch", testNameSearch),
        ("testNoResults", testNoResults),
    ]
}

extension TargetTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TargetTests = [
        ("testBasicAdd", testBasicAdd),
        ("testDependAdd", testDependAdd),
        ("testSystemAdd", testSystemAdd),
        ("testTargetRemove", testTargetRemove),
    ]
}

extension TestTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TestTests = [
        ("testGenerateList", testGenerateList),
    ]
}

extension ToolsVersionTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ToolsVersionTests = [
        ("testGet", testGet),
        ("testUpdate", testUpdate),
    ]
}

extension UpdateTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UpdateTests = [
        ("testUpdate", testUpdate),
        ("testUpdateSingle", testUpdateSingle),
    ]
}

extension VersionTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__VersionTests = [
        ("testVersion", testVersion),
    ]
}

extension XcTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__XcTests = [
        ("testXc", testXc),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AddTests.__allTests__AddTests),
        testCase(BuildTests.__allTests__BuildTests),
        testCase(CleanTests.__allTests__CleanTests),
        testCase(ConfigTests.__allTests__ConfigTests),
        testCase(DumpTests.__allTests__DumpTests),
        testCase(GenerateTestListTests.__allTests__GenerateTestListTests),
        testCase(InitTests.__allTests__InitTests),
        testCase(NewTests.__allTests__NewTests),
        testCase(OutdatedTests.__allTests__OutdatedTests),
        testCase(ProductTests.__allTests__ProductTests),
        testCase(RegistryTests.__allTests__RegistryTests),
        testCase(RemoveTests.__allTests__RemoveTests),
        testCase(ResolveTests.__allTests__ResolveTests),
        testCase(RunTests.__allTests__RunTests),
        testCase(SearchTests.__allTests__SearchTests),
        testCase(TargetTests.__allTests__TargetTests),
        testCase(TestTests.__allTests__TestTests),
        testCase(ToolsVersionTests.__allTests__ToolsVersionTests),
        testCase(UpdateTests.__allTests__UpdateTests),
        testCase(VersionTests.__allTests__VersionTests),
        testCase(XcTests.__allTests__XcTests),
    ]
}
#endif
