#if !canImport(ObjectiveC)
import XCTest

extension BuildTransformTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BuildTransformTests = [
        ("testCompile", testCompile),
        ("testCompileC", testCompileC),
        ("testError", testError),
        ("testLink", testLink),
        ("testLinkerError", testLinkerError),
        ("testNoteNoCode", testNoteNoCode),
        ("testNoteOtherModule", testNoteOtherModule),
        ("testPackageError", testPackageError),
        ("testPCHError", testPCHError),
        ("testRepeated", testRepeated),
        ("testSuggestion", testSuggestion),
        ("testUnusedWarning", testUnusedWarning),
        ("testWarningWithSingleNote", testWarningWithSingleNote),
    ]
}

extension ConfigTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ConfigTests = [
        ("testGet", testGet),
        ("testSet", testSet),
    ]
}

extension InitTransformTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__InitTransformTests = [
        ("testCreateFiles", testCreateFiles),
        ("testCreatePackage", testCreatePackage),
    ]
}

extension LineTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LineTests = [
        ("testAssertionFailureLine", testAssertionFailureLine),
    ]
}

extension PackageDataTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PackageDataTests = [
        ("testModernize4_0", testModernize4_0),
        ("testModernize4_2", testModernize4_2),
        ("testSwiftToolsVersion", testSwiftToolsVersion),
    ]
}

extension PackageLoaderTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PackageLoaderTests = [
        ("test4_0", test4_0),
        ("test4_2", test4_2),
        ("test5_0", test5_0),
        ("testBasic", testBasic),
    ]
}

extension PackageTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PackageTests = [
        ("testAddDependency", testAddDependency),
        ("testAddProduct", testAddProduct),
        ("testAddTarget", testAddTarget),
        ("testDepend", testDepend),
        ("testRemoveDependency", testRemoveDependency),
        ("testRemoveProduct", testRemoveProduct),
        ("testRemoveTarget", testRemoveTarget),
        ("testUpdateDependency", testUpdateDependency),
    ]
}

extension PackageWriterTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PackageWriterTests = [
        ("testCanWrite", testCanWrite),
        ("testCLanguageStandard", testCLanguageStandard),
        ("testCxxLanguageStandard", testCxxLanguageStandard),
        ("testDependencies", testDependencies),
        ("testFull", testFull),
        ("testProducts", testProducts),
        ("testProviders", testProviders),
        ("testSwiftLanguageVersions", testSwiftLanguageVersions),
        ("testTargets", testTargets),
    ]
}

extension RegistryTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RegistryTests = [
        ("testAdd", testAdd),
        ("testAutoRefresh", testAutoRefresh),
        ("testGet", testGet),
        ("testRemove", testRemove),
    ]
}

extension RepositoryReferenceTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RepositoryReferenceTests = [
        ("testGithub", testGithub),
        ("testGitlab", testGitlab),
        ("testMostRecentVersion", testMostRecentVersion),
    ]
}

extension ResolveTransformTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ResolveTransformTests = [
        ("testFetch", testFetch),
        ("testResolve", testResolve),
        ("testUpdate", testUpdate),
    ]
}

extension TestTransformTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TestTransformTests = [
        ("testAllTests", testAllTests),
        ("testInterleavedOutput", testInterleavedOutput),
        ("testMultilineEquality", testMultilineEquality),
        ("testNoFilterMatch", testNoFilterMatch),
        ("testNoTests", testNoTests),
        ("testSelectedTests", testSelectedTests),
        ("testSuitePass", testSuitePass),
        ("testXCTAssert", testXCTAssert),
        ("testXCTEquals", testXCTEquals),
        ("testXCTEqualWithAccuracy", testXCTEqualWithAccuracy),
        ("testXCTFail", testXCTFail),
        ("testXCTFalse", testXCTFalse),
        ("testXCTGreaterThan", testXCTGreaterThan),
        ("testXCTGreaterThanOrEqual", testXCTGreaterThanOrEqual),
        ("testXCTLessThan", testXCTLessThan),
        ("testXCTLessThanOrEqual", testXCTLessThanOrEqual),
        ("testXCTNil", testXCTNil),
        ("testXCTNotEquals", testXCTNotEquals),
        ("testXCTNotEqualWithAccuracy", testXCTNotEqualWithAccuracy),
        ("testXCTNoThrow", testXCTNoThrow),
        ("testXCTNotNil", testXCTNotNil),
        ("testXCTThrow", testXCTThrow),
        ("testXCTTrue", testXCTTrue),
    ]
}

extension VersionTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__VersionTests = [
        ("testBasicParse", testBasicParse),
        ("testComparison", testComparison),
        ("testEquality", testEquality),
        ("testIllegalVersion", testIllegalVersion),
        ("testVParse", testVParse),
    ]
}

extension XcTransformTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__XcTransformTests = [
        ("testGenerate", testGenerate),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(BuildTransformTests.__allTests__BuildTransformTests),
        testCase(ConfigTests.__allTests__ConfigTests),
        testCase(InitTransformTests.__allTests__InitTransformTests),
        testCase(LineTests.__allTests__LineTests),
        testCase(PackageDataTests.__allTests__PackageDataTests),
        testCase(PackageLoaderTests.__allTests__PackageLoaderTests),
        testCase(PackageTests.__allTests__PackageTests),
        testCase(PackageWriterTests.__allTests__PackageWriterTests),
        testCase(RegistryTests.__allTests__RegistryTests),
        testCase(RepositoryReferenceTests.__allTests__RepositoryReferenceTests),
        testCase(ResolveTransformTests.__allTests__ResolveTransformTests),
        testCase(TestTransformTests.__allTests__TestTransformTests),
        testCase(VersionTests.__allTests__VersionTests),
        testCase(XcTransformTests.__allTests__XcTransformTests),
    ]
}
#endif
